app/__init__.py
from flask import Flask 

from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, Marshmallow
from flask_marshmallow import Marshmallow

from flask_cors import CORS
from helpers import JSONEncoder

from flask_login import LoginManager

app = Flask(__name__)




CORS(app)


migrate = Migrate(app, root_db)

ma = Marshmallow(app)

app.register_blueprint(site) 
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, Car, User, car_schema, cars_schema


api = Blueprint('api', __name__, url_prefix='/api') #prefix means that it goes before the slug


@api.route('/cars', methods = ['POST'])
@token_required
def add_car(current_User_token):
    brand = request.json['brand']
    model = request.json['model']
    year = request.json['year']
    color = request.json['color']
    car_token = current_User_token.token

    print(f'BIG TESTER: {current_User_token.token}')

    car = Car(brand, model, year, color, car_token=car_token) #we do_User_token =_User_toked to over-write
    #the previous value for that variable

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

# this route is to bring back all cars in the inventory

@api.route('/cars', methods = ['GET'])
@token_required
def get_all_cars(current_User_token):
    a_car = current_User_token.token
    cars = Car.query.filter_by(car_token = a_car).all()
    response = cars_schema.dump(cars)
    return jsonify(response)

# this route is to bring back one specific car from the inventory
@api.route('/cars/<id>', methods = ['GET'])
@token_required
def get_a_car(current_User_token, id):
    car = Car.query.get(id)
    response = car_schema.dump(car)
    return jsonify(response)


#this route allows us to update a car in case of a mistake

@api.route('/cars/<id>', methods = ['POST', 'PUT'])
@token_required
def update_car_info(current_User_token, id):
    car = Car.query.get(id)
    car.brand = request.json['brand']
    car.model = request.json['model']
    car.year = request.json['year']
    car.color = request.json['color']
    car.car_token = current_User_token.token

    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

# then if we need to delete a car from the companies inventory
@api.route('/cars/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_User_token, id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm

from models import User, db, check_password_hash

from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates') 
@auth.route('/signup', methods = ['GET', 'POST']) 

def signup():
    form = UserLoginForm()   

    try:  
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data 
            print(email, password)
            Administrator = User(email, password = password)
            

            db.session.add(Administrator) 
            db.session.commit()

            flash(f'You have successfully created an Administrator account {email}', 'Administrator-created')
            return redirect(url_for('site.home')) 
    except:
        raise Exception('Invalid form data: Please check your form.')
    return render_template('sign_up.html', form=form) 


@auth.route('/signin', methods = ['GET', 'POST'])

def signin():
    form = UserLoginForm()

    try:  
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data 
            print(email, password)
            
            logged_user = User.query.filter(User.email == email).first() 
            if logged_user and check_password_hash(logged_user.password, password):
                
                login_user(logged_user)
                flash('You successfully signed in.')
                return redirect(url_for('site.profile'))
            else:
                flash(f"You have failed to get in, you must not be an employee.")
    except:
        raise Exception ('Somthing went wrong, please check your sign in information')
    return render_template('sign_in.html', form = form)
            

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site',__name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/inventory')
def inventory():
    return render_template ('inventory.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Your Website{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    
    <img class="bg" src="{{ url_for('static', filename='photos/car_bg.jpg') }}" alt="My Photo">

    <nav class="navbar">
        <a class="navbar-title" href="{{ url_for('site.home')}}">BMW of Carsville</a>
        <a class="navbar-button" href="{{ url_for('site.home')}}">Home</a>
        <a class="navbar-button" href="{{ url_for('site.inventory')}}">Inventory</a>
        <a class="navbar-button" href="{{ url_for('site.home')}}">About Us</a>
        <a class="navbar-button" href="{{ url_for('site.home')}}">Contact Us</a>
                    <div class="navbar-auth">
                            {% if current_user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('auth.logout')}}">Log Out</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('site.profile')}}">Profile</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('auth.signin')}}">Sign In</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('auth.signup')}}">Sign Up</a>
                                </li>
                            {% endif %}
                    </div>
        </ul>
    </nav>
   
    {% block content %}
    {% endblock %}

</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

      
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}
    </div>
</form>